# Site settings
title: Gentoo 中文社区
#email: service@gentoo.org.cn
description: Gentoo 中文社区
baseurl: ""
url: "https://www.gentoo.org.cn"
github_username:  gentoo-zh
icp: ""

# Build settings
markdown: kramdown
permalink: pretty

gems:
    - jekyll-paginate

exclude: [hooks]
